version: '3.8'
services:
  database:
    image: timescale/timescaledb:latest-pg14
    environment:
      POSTGRES_DB: ldc
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./database/data:/var/lib/postgresql/data
  grafana:
    image: grafana/grafana-oss:latest-ubuntu
    ports:
      - "3000:3000"
    links:
      - database