version: '3.8'
services:
  grafana:
    build: './grafana'
    container_name: 'grafana'
    volumes:
      - ./grafana_data/:/var/lib/grafana
    ports:
      - '3000:3000'
    env_file:
      - .env
  ldc:
    build:
      context: ./
      dockerfile: ./ldc/Dockerfile
    container_name: 'ldc'
    env_file:
      - .env