version: '3.8'
services:
  grafana:
    container_name: 'grafana'
    build: './grafana'
    volumes:
      - type: bind
        source: ./grafana_data
        target: /var/lib/grafana
    ports:
      - '3000:3000'
    env_file:
      - .env
  ldc:
    container_name: 'ldc'
    build:
      context: ./
      dockerfile: ./ldc/Dockerfile
    env_file:
      - .env