"""Initial

Revision ID: f17e41937c9c
Revises: 
Create Date: 2021-12-15 00:48:08.862335

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f17e41937c9c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('channel_type', postgresql.ENUM('STAGE', 'VOICE', 'TEXT', name='type'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )

    op.create_table('events',
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.Column('event_type', postgresql.ENUM('MESSAGE_SEND', 'MESSAGE_DELETE', 'MESSAGE_EDIT', 'MEMBER_JOIN', 'MEMBER_LEAVE', 'MEMBER_BANNED', 'MEMBER_UNBANNED', 'VC_JOIN', 'VC_LEAVE', 'REACT_ADD', 'REACT_REMOVE', name='event_type'), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('observed_at'),
    sa.UniqueConstraint('observed_at')
    )

    op.create_index('event_channel_id', 'events', [sa.text('(meta->>\'channel_id\')')], postgresql_using='hash')
    op.create_index('event_emoji_id', 'events', [sa.text('(meta->>\'emoji_id\')')], postgresql_using='hash')

    op.execute("SELECT create_hypertable('events', 'observed_at');")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    op.drop_table('channels')
    # ### end Alembic commands ###
