{
 "title": "Global",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "target_channel",
    "label": "Channel",
    "query": "SELECT id::varchar AS __value, name AS __text FROM channels;"
   },
   {
    "name": "target_event_type",
    "label": "Event Type",
    "query": "SELECT unnest(enum_range(NULL::event_type));"
   }
  ]
 },
 "panels": [
  {
   "title": "Events",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket_gapfill('30 seconds', observed_at) AS time,\n  COALESCE(COUNT(*), 0) AS \"All\"\nFROM\n  events\nWHERE\n  $__timeFilter(observed_at) AND meta->>'channel_id' IN ($target_channel)\n  AND event_type IN ($target_event_type)\nGROUP BY time\nORDER BY time\n"
    }
   ]
  },
  {
   "title": "Activity over the last 30 seconds",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket('30 seconds', observed_at) AS time,\n  COUNT(*)\nFROM\n  events\nWHERE\n  $__timeFilter(observed_at) AND meta->>'channel_id' IN ($target_channel)\n  AND event_type IN ($target_event_type)\nGROUP BY time\n"
    }
   ]
  },
  {
   "title": "Events per period",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 6, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  COUNT(*)\r\nFROM\r\n  events\r\nWHERE $__timeFilter(observed_at) AND meta->>'channel_id' IN ($target_channel) AND event_type IN ($target_event_type)"
    }
   ]
  },
  {
   "title": "Most common reaction",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 11, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\r\n   COALESCE(name, meta->>'emoji_id') AS \"Reaction\",\r\n    COUNT(*) AS \"Count\"\r\nFROM events\r\nLEFT JOIN emojis ON (meta->>'emoji_id') = id::varchar\r\nWHERE (event_type = 'REACT_ADD' OR event_type = 'REACT_REMOVE') AND $__timeFilter(observed_at)\r\nGROUP BY meta->>'emoji_id', name\r\nORDER BY \"Count\" DESC\r\nLIMIT 5"
    }
   ]
  },
  {
   "title": "Events per channel",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 16, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\r\n       name as \"Name\",\r\n       COUNT(*) AS \"Events\"\r\nFROM events\r\nINNER JOIN channels ON id = (meta->>'channel_id')::bigint\r\nWHERE $__timeFilter(observed_at)\r\nGROUP BY name, meta->>'channel_id'\r\nORDER BY \"Events\" DESC\r\nLIMIT 5\r\n"
    }
   ]
  }
 ]
}